### ISSUE TITLE
Transaction_Id from cash payments

### ISSUE THREAD

**Issue by AngeloMateus** [square/react-native-square-reader-sdk#100]
### Describe the functionality you would like to see

In the checkout results, could we have the transaction_id or Payment_id for cash payments so we can then issue a refund programmatically using the refunds API?

### How would this feature make the plugin more useful?

You can issue refunds for cash as opposed to just for card payments.

**Comment by StephenJosey** [comment]
Hi @AngeloMateus currently cash transactions on the ReaderSDK happen asynchronously, which means that the server hasn't created the `transaction_id` before returning control back to your application. Instead, you will receive a `clientTransactionId` which you can use to look up the transaction. It will be part of the Transactions API with the `client_id` field.

Please let me know if that doesn't make sense, or if you have additional questions!
