### ISSUE TITLE
Disable modal after successful transaction

### ISSUE THREAD

**Issue by AngeloMateus** [square/react-native-square-reader-sdk#104]
### Describe the functionality you would like to see
Option to disable change modal after a successful transaction. This doensn't happen in Android and only one modal can be visible at a time in IOS. Moreover the modal is on a timer with no way to keep it visible for longer or dissmiss it.

### How would this feature make the plugin more useful?
Better user experience.

**Comment by StephenJosey** [comment]
Appreciate the feedback, I'll share this with the team.

**Comment by CharmisG** [comment]
Thank you for your feedback. We have shared the feedback with our team.
