### ISSUE TITLE
Unable to provide signature

### ISSUE THREAD

**Issue by nataliepan** [square/react-native-square-reader-sdk#106]
### Describe the issue
Signature screen does not allow use to create smooth lines. 
We've stripped our App to only the square SDK.
We call startCheckoutAsync at within App.jsx opens the Square SDK, after successfully collecting payment the signature screen opens. When trying to sign, the finger does not create smooth lines, but what appears to be dragged dots. Signature screen, is also dragged and closed with moving the finger downward while signing.

 
### To Reproduce
  1. Initialize the SDK, ensure signature settings are on
  2. Process a successful payment
  3. Get to the signature screen
  4. try signing

![File](https://user-images.githubusercontent.com/4775411/70569692-47d92180-1b4f-11ea-95dc-b10bf29a92de.jpg)

**Comment by mgd722** [comment]
seconded. i just installed the demo app and didn't change anything and had the same issue.

**Comment by okenshields** [comment]
Thanks for reporting the issue. We are currently investigating and will get back to you.

**Comment by StephenJosey** [comment]
Hey folks, this should be resolved in the latest Reader SDK release for iOS (1.3.7). Could you confirm that this resolves it for you?
