### ISSUE TITLE
Error: Program type already present: com.jakewharton.threetenabp.AndroidThreeTen

### ISSUE THREAD

**Issue by katyechhj** [square/react-native-square-reader-sdk#114]
### Describe the issue

I am unable to run my project because of an error with AndroidThreeTen and as far as I can tell, this library is the only thing using it. Does anyone have any idea where to go with this? Thanks! 

  Error log details:
  ```
AGPBI: {"kind":"error","text":"Program type already present: com.jakewharton.threetenabp.AndroidThreeTen","sources":[{}],"tool":"D8"}
> Task :app:buildInfoGeneratorDebug
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.jakewharton.threetenabp.AndroidThreeTen
  ```

### Expected behavior
The project should build and run correctly. 

**Environment (please complete the following information):**
  - platform: Android
  - dev environment: MacOS
  - Reader SDK version: 1.3.0 and 1.3.1
  - Android Studio: v3.4.2
  - Gradle: v5.5.1

  In addition: Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 135.21 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
```

### Screenshots

![image](https://user-images.githubusercontent.com/39961933/72742958-ba8ae300-3b78-11ea-8f57-ddc0a2822e34.png)

**Comment by jgorecki** [comment]
Following

**Comment by katyechhj** [comment]
It seems this was a problem with an outdated version of Gradle and/or Android Studio! As soon as it updated everything, it worked!
