### ISSUE TITLE
framework not found SquareReaderSDK

### ISSUE THREAD

**Issue by DungBuiDeveloper** [square/react-native-square-reader-sdk#115]
1  I follow the document step by step
https://github.com/square/react-native-square-reader-sdk/tree/master/reader-sdk-react-native-quickstart
and step 2 "pod install" not working. ( new project )
2. I used example code in the link above, still same error occured

https://prnt.sc/rbd5lt
https://prnt.sc/rbd5sg

i see header search path not include lib

i tried to insert manually but still not working too
https://prnt.sc/rbd64o
Please help me!

Environment (please complete the following information):

System:
OS: macOS 10.15.3
CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
Memory: 43.11 MB / 8.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.3 - /usr/local/bin/node
Yarn: 1.17.3 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
Android SDK:
API Levels: 23, 24, 25, 26, 27, 28, 29
Build Tools: 27.0.3, 28.0.3, 29.0.0
System Images: android-24 | Google Play Intel x86 Atom
IDEs:
Android Studio: 3.5 AI-191.8026.42.35.6010548
Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
npmPackages:
react: 16.9.0 => 16.9.0
react-native: 0.61.5 => 0.61.5
npmGlobalPackages:
react-native-cli: 2.0.1
react-native-rename: 2.4.1

**Comment by mootrichard** [comment]
I would try running `yarn` or `yarn install` at the root of `/reader-sdk-react-native-quickstart` _before_ running `pod install` in the iOS folder. 

If you _have_ done that and are you still getting these errors, please detail out the steps that you're taking and what is being logged to your console at each stage in order to better help us in troubleshooting what is happening.

**Comment by DungBuiDeveloper** [comment]
for anyone error same me 

make step 3 curl from ruby  in ios folder not root project and make sure tartget build 11.0

**Comment by rahamin1** [comment]
I have done step 2 in: https://developer.squareup.com/docs/reader-sdk/build-on-ios#step-2-install-reader-sdk

Then, I wanted to do step 3 (https://developer.squareup.com/docs/reader-sdk/build-on-ios#step-3-configure-your-ios-project-for-reader-sdk) but I don't find SquareReaderSDK.framework.

So, I followed your advice:
> make step 3 curl from ruby in ios folder not root project and make sure target build 11.0

But I still cannot find the framework file.

Here is what I see in the project tree (the frameworks folder is empty):
![image](https://user-images.githubusercontent.com/15701347/80943571-29bad900-8df0-11ea-8ae5-f26be104835b.png)

And this is what I have in General -> Frameworks, Libraries and Embedded Content:
![image](https://user-images.githubusercontent.com/15701347/80943625-52db6980-8df0-11ea-85a9-66c7e55878a8.png)

Any idea what I should do?

**Comment by StephenJosey** [comment]
@rahamin1 what do you see when you run the ruby terminal command? Do you see it actually download the framework (the terminal should let you know)?

**Comment by rahamin1** [comment]
It seems so:
```
 [100.0% complete] [####################################################################################################]
Installed version 1.3.7: /Users/user172615/Documents/plumpclient/SquareReaderSDK.framework
```

**Comment by StephenJosey** [comment]
So if you did `ls` do you see the `SquareReaderSDK.framework` there? It looks like it successfully installed, perhaps it's not in the correct directory?

Also, based on the above screenshot, it looks like you're opening the RNReaderSDK workspace directly, rather than trying to install it in your own project, or am I seeing wrong?

**Comment by rahamin1** [comment]
Yes, its there. And I should have added it using 'Add Other'. Added now, thanks.

> Also, based on the above screenshot, it looks like you're opening the RNReaderSDK workspace directly, rather than trying to install it in your own project, or am I seeing wrong?
No, I am not.

Thank you (again... :), Stephen!
