### ISSUE TITLE
  Library not loaded: @rpath/CorePaymentCard.framework/CorePaymentCard

### ISSUE THREAD

**Issue by DungBuiDeveloper** [square/react-native-square-reader-sdk#116]
i try build on real device and  Library not loaded: @rpath/CorePaymentCard.framework/CorePaymentCard

https://prnt.sc/rcdd44

**Comment by DungBuiDeveloper** [comment]
@

**Comment by ajayPris** [comment]
i have facing same error and couldn't able to run a build in real device and as well as not able to upload a build. i also followed all steps of READER SDK (Build on iOS). Please help to resolve this bug.

Square Reader SDK Version is : 1.4.7
Xcode version is :12.3 (iOS Native)

![Screen Shot 2021-02-05 at 11 49 35 AM](https://user-images.githubusercontent.com/24670996/107036144-28836600-67df-11eb-9e3b-8dc930afff56.png)

**Comment by domhacking** [comment]
@DungBuiDeveloper & @ajayPris, were you able to resolve this issue? I am getting the same error. Thanks for your help!

**Comment by slxmmy999** [comment]
This is an old thread but has anyone found a solution? I am facing the same issue though I am sure it is most likely user error on my part.

**Comment by TopIvanAbramov** [comment]
I am facing the same issues integrating via SPM
