### ISSUE TITLE
Usage of UIWebView prevents uploading app to Apple's App Store Connect

### ISSUE THREAD

**Issue by rahamin1** [square/react-native-square-reader-sdk#120]
### The problem

- I am trying to build and upload an app to Apple's App Store Connect, and I am getting the following error:
`ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).`
- I found the following in SO: https://stackoverflow.com/a/57730461/5532513
- Running the following:
```
cd ~/Library/Developer/Xcode/Archives/<date>/myapp.xcarchive/Products/Applications/myapp.app

for framework in Frameworks/*.framework; do
  fname=$(basename $framework .framework)
  echo $fname
  nm $framework/$fname | grep UIWeb
done
```
- I get:
```
CorePaymentCard
SquareCore
SquareInAppPaymentsSDK
SquareReader
SquareReaderSDK
```

### explanation in the Apple developer site
https://apple.co/3eV0FgZ

### Any suggestion on what to do?

**Comment by AngeloMateus** [comment]
Was just about to release an app with the SDK and got ITMS-90809 as well, is there a workaround to this?

**Comment by StephenJosey** [comment]
This should be resolved in the latest version of ReaderSDK - are you folks using the latest version?

**Comment by rahamin1** [comment]
@StephenJosey 

- As I wrote above, the problem seems to be in both `react-native-square-reader-sdk` and `in-app-payments-react-native-plugin` (see https://bit.ly/2XGuk7Y)
- I am using version 1.3.1 of both packages

@AngeloMateus 
- Do you also use  `in-app-payments-react-native-plugin`? 
- Which version of react-native are you using?

**Comment by StephenJosey** [comment]
In the script you have you're printing every package (`echo $fname`), it seems, it does not mean it's in each package. It looks like the reference was removed in 1.3.7 for ReaderSDK (https://developer.squareup.com/docs/changelog/mobile-logs/2020-02-26), so you need to update to at least that version (although 1.3.8 is the latest).

**Comment by rahamin1** [comment]
Thanks Stephen.

I thought that 1.3.1 is the latest version.. This is the latest version in the npm site.

Now I see that the latest is 1.3.9 for the reader sdk and 1.4.0 for the In-App Payments SDK.
I will try these versions and update here.

**Comment by rahamin1** [comment]
Thanks Stephen.

I will try the latest commits of both packages.

**Comment by rahamin1** [comment]
The latest version in npm is 1.3.1 for both packages, so I have replaced the relevant lines in package.json with:
```
"react-native-square-in-app-payments": "git://github.com/square/in-app-payments-react-native-plugin.git#c4eebc7d65e3ba5f32cbfbdf5354e78c4f50df30",
"react-native-square-reader-sdk": "git://github.com/square/react-native-square-reader-sdk.git#d13aa44b55bcbf9c2f1ff21d580649278b9b571a",
```

I am still getting the same errors as in https://github.com/square/react-native-square-reader-sdk/issues/120#issue-631717972.

**Comment by StephenJosey** [comment]
Sorry, I think we're referring to different things. You're talking about the react native plugin version, I'm talking about the iOS ReaderSDK version - which the react native plugin uses. You should be installing the iOS SDK as per Step 5: https://github.com/square/react-native-square-reader-sdk/blob/master/docs/get-started.md#step-5-install-reader-sdk-for-ios, which will install the latest version. You can see further instructions for reinstalling the iOS SDK here: https://developer.squareup.com/docs/reader-sdk/upgrade-reader-sdk#install-a-new-version-of-the-framework

**Comment by rahamin1** [comment]
Thanks Stephen. I will try.

**Comment by rahamin1** [comment]
Thanks Stephen. 

I followed https://developer.squareup.com/docs/reader-sdk/upgrade-reader-sdk#install-a-new-version-of-the-framework and the command 
```
ruby <(curl https://connect.squareup.com/readersdk-installer
) install --app-id {APP_ID} --repo-password {REPO_PASSWORD} —-version    {VERSION}
```
Prints that I am using version 1.3.8.

But the App Connect error remains:

`ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).`

**Comment by gallifilo** [comment]
For me it works and I was able to submit now by updating the iOS ReaderSDK from 1.3.1 to 1.3.8
with
react-native: 0.61.5 
square-sdk-react-native: 1.3.1
square-sdk-ios: 1.3.8

**Comment by rahamin1** [comment]
Thanks @gallifilo. Strange. I will try again (I am currently using 0.59.9 and I have other problems, so I am trying to migrate to 0.62.2 first, so it will take some time).

BTW, Do you also use in-app-payments-react-native-plugin?

**Comment by koshovnik** [comment]
I confirm. Was able to push a build to test flight with:
{
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-square-reader-sdk": "^1.3.1"
}
and square-sdk-ios: 1.3.8

I do not use in-app-payments-react-native-plugin.

**Comment by gallifilo** [comment]
@rahamin1 no I do not use  in-app-payments-react-native-plugin. 
So you might want to upgrade your react-native version as from 0.60.0 they have separated the WebView
https://github.com/facebook/react-native/releases/tag/v0.60.0

**Comment by rahamin1** [comment]
I am trying to upgrade to 0.62.2. Other problems there...  (https://github.com/square/react-native-square-reader-sdk/issues/121)

What do you mean by `they have separated the WebView`?

**Comment by rahamin1** [comment]
As @gallifilo wrote above, the problem doesn't exist in newer react-native version. I tested it in 0.62.2.
