### ISSUE TITLE
"Square needs device storage" Android

### ISSUE THREAD

**Issue by mattknappchhj** [square/react-native-square-reader-sdk#158]
### Describe the issue

Android users are receiving "Square needs device storage" error, even with storage permissions accepted and showing as accepted in settings.

### Expected behavior

**Environment (please complete the following information):**

platform: Android
OS: Android 12
Reader SDK version: 1.4.0

### Additional context

<img width="398" alt="Screen Shot 2022-01-14 at 12 58 09 PM" src="https://user-images.githubusercontent.com/16048871/149563094-20354e1f-26f0-421c-b534-cd8609a4fe3a.png">

<img width="400" alt="Screen Shot 2022-01-14 at 1 01 00 PM" src="https://user-images.githubusercontent.com/16048871/149563149-2feb1fed-f85c-4f05-82a8-143167157636.png">

**Comment by vishwajitshep0815** [comment]
Can you please replicate and provide specific steps for the issue, because I couldn't replicate it at my end?
