### ISSUE TITLE
DebugSymbolsPath not found

### ISSUE THREAD

**Issue by smalik02** [square/react-native-square-reader-sdk#182]
### Describe the issue
 Whenever I try to compile the project, it fails with DebugSymbolsPath not found. I looked at the Info.plist in SquareReaderSDK  framework, and it has new added attributes for DebugSymbolsPath. However, they aren't present in the folders themselves. 
  Error log details:
  ```
  Missing path (.../ios/SquareReaderSDK.xcframework/ios-x86_64-simulator/dSYMs) from XCFramework 'SquareReaderSDK.xcframework' as defined by 'DebugSymbolsPath' in its `Info.plist` file (in target  'app' from project 'app')
  ```

### To Reproduce

  1. Clone the sample project
  2. Install the sdk
  3. compile ios by `react-native run-ios `
  4. Error is shown: `Missing path (.../test-sq/react-native-square-reader-sdk/reader-sdk-react-native-quickstart/ios/SquareReaderSDK.xcframework/ios-x86_64-simulator/dSYMs) from XCFramework 'SquareReaderSDK.xcframework' as defined by 'DebugSymbolsPath' in its `Info.plist` file (in target 'RNReaderSDKSample' from project 'RNReaderSDKSample')`

**Comment by butmitchtho** [comment]
+1 experiencing the same issue.

**Comment by JayVishEsoft** [comment]
I too had same issue, tho I created a folder named as 'dSYMs' in the below path in ios folder. 
path => /ios/SquareReaderSDK.xcframework/ios-x86_64-simulator/dSYMs       <== here!.
and doing this resovled the issue

**Comment by CharmisG** [comment]
@smalik02 @butmitchtho 
Sorry for the delay !!
Can you please pull latest code it's resolved !!
