### ISSUE TITLE
Not able to payment using sdk

### ISSUE THREAD

**Issue by sahilshah-canwill** [square/react-native-square-reader-sdk#186]
### Describe the issue

 I am not able to make payments with square reader SDK for iOS - It's very frustrating guys - we are on a point - please provide us with some guidance asap - please

  Error log details:
  ```
 USAGE_ERROR:checkout_present_from_presenting_view_controller:The checkout controller cannot be presented from a view controller which is already presenting another view controller.

This device is not currently authorized to accept payments with Square.

  ```

### To Reproduce

  Steps to reproduce the issue.

  For example - 
  1. Initialize the SDK
  1. Get a valid authz code
  1. Call `await RNReaderSDKAuthorization.authorize(authCode);` and failed

  Here the piece of code that reproduce the issue.

  ```javascript
  const { RNReaderSDKAuthorization, RNReaderSDKCheckout, RNReaderSDKReaderSettings } = NativeModules;

  export async function authorizeAsync(authCode) {
    try {
      // it looks like that RNReaderSDKAuthorization is undefined
      return await RNReaderSDKAuthorization.authorize(authCode);
    } catch (ex) {
      throw createReaderSDKError(ex);
    }
  }
  ```

### Expected behavior
 The authorization should complete successfully with my valid authz token.

**Environment (please complete the following information):**

**Comment by CharmisG** [comment]
@sahilshah-canwill 
Sorry for the delay !!
Can you please pull latest code it's resolved !!
