### ISSUE TITLE
authorizeAsync(authCode) throws error (iOS)

### ISSUE THREAD

**Issue by wuiidl** [square/react-native-square-reader-sdk#19]
Trying to authorize the reader returns 

**Cannot read property 'authorize' of undefined.**

When I try to authorize the reader with the correct location and oauth param it returns an exception.

To me it looks like the SDK framework is not being instantiated correctly. Android works as expected.

```
const { RNReaderSDKAuthorization, RNReaderSDKCheckout, RNReaderSDKReaderSettings } = NativeModules;

export async function authorizeAsync(authCode) {
  try {
// it looks like that RNReaderSDKAuthorization is undefined
    return await RNReaderSDKAuthorization.authorize(authCode);
  } catch (ex) {
    throw createReaderSDKError(ex);
  }
}

```
The permissions have been granted on app start.

My workflow is:
1. Request mobile auth code from API
2. authorize async.
3. let ReaderSDK checkout handle the rest

**EDIT:**

This is my AppDelegate.m main method.

```
#import "AppDelegate.h"
#import <CodePush/CodePush.h>
#import <Firebase.h>

#import "RNFirebaseNotifications.h" 
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@import SquareReaderSDK;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [RNFirebaseNotifications configure];
  [SQRDReaderSDK initializeWithApplicationLaunchOptions:launchOptions];
  
  NSURL *jsCodeLocation;
  
  #ifdef DEBUG
    jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.bundle?platform=ios&dev=true"];
  #else
    jsCodeLocation = [CodePush bundleURL];
  #endif

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"nativeApp"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end
```

**UPDATE 2:**
After consulting the Square-slack channel, I ran react-native link again. It looks like something happened because now the build fails with the following:

`(....)/Build/Intermediates.noindex/nativeApp.build/Debug-iphonesimulator/nativeApp.build/Script-86134DB72160763400358288.sh: line 2: /SquareReaderSDK.framework/setup: No such file or directory`

Upon investigation, it turns out the only file that is in that folder that looks remotely close to SquareReaderSDK.framework is SquareReaderSDK.framework.xcent.

**UPDATE 3**

This fails also with the provided sample app. It looks like to script that calls the setup method has the wrong environment variables or the *.framework file is not copied.

**Comment by hukid** [comment]
The error `(....)/Build/Intermediates.noindex/nativeApp.build/Debug-iphonesimulator/nativeApp.build/Script-86134DB72160763400358288.sh: line 2: /SquareReaderSDK.framework/setup: No such file or directory`  is due to `"${FRAMEWORKS}/SquareReaderSDK.framework/setup"` not in the separate line.

Follow up with @wuiidl offline for the plugin linking issue, and will update once the issue is resolved.

**Comment by hukid** [comment]
The root cause is that `react-native link react-native-square-reader-sdk` seems not able to add link of libRNReaderSDK.a to the project when cocoapods is configured.

The solution is to manually add **libRNReaderSDK.a** to your project's `Build Phases -> Link Binary With Libraries` . You can find the **libRNReaderSDK.a** from `Libraries -> RNReaderSDK.xcodeproj -> Products`

**Comment by wuiidl** [comment]
Thank you for helping me! It works perfectly.

**Comment by hukid** [comment]
#21
