### ISSUE TITLE
How can I map the transaction made by SDK with square order? 

### ISSUE THREAD

**Issue by GokulselvanR** [square/react-native-square-reader-sdk#201]
### I can able to make a payment using react-native-square-reader-sdk and also can able to create orders in Square using the create order API. Is there a way to map between this transactions with the orders? If yes how ? If no what are the alternatives ?

We Tried: 
   Paying an order using CASH with Notes as "paid" after the successfull payment on SDK. But It create a duplicate transactions in SQUARE Dashboard.

Any suggesstions?

**Comment by fka3** [comment]
The react plugin wraps Reader SDK v1, which predates the Orders API... but you can still do this with the [PayOrder](https://developer.squareup.com/docs/orders-api/pay-for-orders) endpoint.  You would create the order, use reader SDK to take a payment, and then pass that payment_id to PayOrder.
