### ISSUE TITLE
App crashes when trying to use the Square Stand

### ISSUE THREAD

**Issue by smalik02** [square/react-native-square-reader-sdk#219]
### Describe the issue

  Our product was approved by Square & the Apple team. We added the PPID #s to the info.plist file. We expected the reader sdk to connect with the square stand automatically & process the payment. However, whenever we try to start the checkout process, the app crashes. 

Here is a link to the issue on Sentry: https://tabletab.sentry.io/share/issue/f30953fea1a34b0d86c04513f1920dc7/

### To Reproduce

  Steps to reproduce the issue.
  1. Open the reader-sdk app with the square stand
  1. Start the checkout process `const checkoutResult: CheckoutResult = await startCheckoutAsync(
        checkoutParams
      );`. App crashes

### Expected behavior
It should present the checkout screen.

**Environment (please complete the following information):**

  - platform: iOS - iPad12,1
  - OS and version: iOS 16.2
  - Reader SDK version: 1.6.9

**Comment by CharmisG** [comment]
@smalik02 
Can you please check in latest update and let us know if you are still facing same issue.

**Comment by smalik02** [comment]
using a latest version for this library?

**Comment by brandonjenniges** [comment]
@smalik02 Can you try again to see if this issue still happens on ReaderSDK 1.6.9?  We had a fix for this in 1.6.9 and I don't see any crash logs for it in that version.

Can you also confirm you updated your Info.plist with the values as shown [here](https://developer.squareup.com/docs/reader-sdk/cookbook/square-stand).

Additionally if you can provide any surrounding context to what you're passing into the `checkoutParams` that might help debug this issue.
