### ISSUE TITLE
manual_card_entry is not shown in ios platform but shown in android side.

### ISSUE THREAD

**Issue by mAwaisKhan299** [square/react-native-square-reader-sdk#231]
### Description
I am experiencing an issue with the Square Reader SDK on React Native where the `manual_card_entry` payment type is displayed as an option on Android devices but not on iOS. Below are the details of my implementation and observations.

### Environment
- **SDK Version**: [1.7.2]
- **React Native Version**: [0.72.3]
- **Devices/OS Versions**: Android 11 (Pixel 4), iOS 17.2 (iPhone 15)

### Expected Behavior
All specified `additionalPaymentTypes` including `cash`, `other`, and `manual_card_entry` should be displayed on both iOS and Android platforms.

### Actual Behavior
On Android, all options (`cash`, `other`, `manual_card_entry`) are displayed correctly. However, on iOS, the `manual_card_entry` option does not appear.

### Steps to Reproduce
1. Initialize the SDK with the following parameters:
   ```javascript
   const checkoutParams = {
      amountMoney: {
        amount: 100,
        currencyCode: "USD"
      },
      skipReceipt: false,
      collectSignature: true,
      allowSplitTender: false,
      delayCapture: false,
      note: "Hello 💳 💰 World!",
      tipSettings: {
        showCustomTipField: true,
        showSeparateTipScreen: true,
        tipPercentages: [15, 20, 30],
      },
      additionalPaymentTypes: ["cash", "other", "manual_card_entry"],
    };
![Simulator Screenshot - iPhone 15 - 2024-05-13 at 10 39 18](https://github.com/square/react-native-square-reader-sdk/assets/81459884/80be8d80-60a3-4e5a-ba9f-6ca94fba5b1d)
![Screenshot_20240513-103918_Rosas](https://github.com/square/react-native-square-reader-sdk/assets/81459884/f58e5d74-008b-4ad6-b212-ab7fac566255)

**Comment by Saqib-paklogics** [comment]
It was not showing because my account was not activated and the account was not fully created. When the account was fully created, it started showing.

**Comment by mAwaisKhan299** [comment]
It was not showing because my account was not activated and the account was not fully created. When the account was fully created, it started showing.
