### ISSUE TITLE
Reader SDK Availability outsite US

### ISSUE THREAD

**Issue by rolfdalhaug** [square/react-native-square-reader-sdk#27]
Hi

We're looking at Square / Reader SDK for a project we're starting in a couple of months. Do you have a time-frame for making this available within other regions specifically the UK?..

**Comment by StephenJosey** [comment]
Glad to hear you're interested in our ReaderSDK! We would love for it to be available outside the US as well, but unfortunately we don't have a public timeline at this moment. We'll definitely announce when it's made available elsewhere.
