### ISSUE TITLE
'tipSettings' is not an object error for no good reason.

### ISSUE THREAD

**Issue by SudoPlz** [square/react-native-square-reader-sdk#34]
If I call `startCheckoutAsync` with the following check param:

	{
	    additionalPaymentTypes =     (
	        "manual_card_entry"
	    );
	    allowSplitTender = 0;
	    alwaysRequireSignature = 0;
	    amountMoney =     {
	        amount = 1;
	        currencyCode = USD;
	    };
	    note = "bla bla";
	    skipReceipt = 1;
	    tipSettings = "<null>"; // <-- this is set to null in javascript
	}

I will always get an error `'tipSettings' is not an object` coming from this line of code
https://github.com/square/react-native-square-reader-sdk/blob/f19f68da781cd132da69d694322ccddea6821bd0/ios/RNReaderSDKCheckout.m#L161

Therefore the `jsCheckoutParameters[@"tipSettings"]` line won't do the trick. It looks like I'll have to set the js value to `undefined` in js. Is that intended behaviour?
In the [tipSettings doc](https://github.com/square/react-native-square-reader-sdk/blob/master/docs/reference.md#checkoutparameter) it says that the default value is null, but looks like the default value should be `undefined` or the checks in native code should be different.

**Comment by hukid** [comment]
you are right, we should update the docs to mark it `undefined` instead of `null`. I will fix the docs.

**Comment by SudoPlz** [comment]
Thanks @hukid
