### ISSUE TITLE
Connected reader detection

### ISSUE THREAD

**Issue by jbcullis** [square/react-native-square-reader-sdk#38]
Is there a way we can call the sdk to see if a reader is connected?

**Comment by StephenJosey** [comment]
No, currently there is not a way to tell if a reader is connected programmatically via the SDK.

**Comment by zacdemi** [comment]
@StephenJosey We also need to be able to know If a reader is connected or not. Do you have a suggestion of the best way to do this? Could it be done with [react-native-ble-plx](https://github.com/dotintent/react-native-ble-plx)?
