### ISSUE TITLE
RN 0.57.8 throws error

### ISSUE THREAD

**Issue by jbcullis** [square/react-native-square-reader-sdk#40]
Using a clean build of a test project, I follow the install instructions and get the following error:

Android dependency 'com.android.support:support-v4' has different version for the compile (26.0.2) and runtime (26.1.0) classpath. You should manually set the same version via DependencyResolution

** UPDATE **
As per the full android setup guide, here are the settings that needed to be set:

android/build.gradle:
    ext {
        buildToolsVersion = "26.0.2"
        minSdkVersion = 21
        compileSdkVersion = 26
        targetSdkVersion = 26
        supportLibVersion = "26.0.2"
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }

Then in android/app/build.gradle under dependencies:
    compile ("com.android.support:support-v4:26.0.2") {
        force = true
    }

We need an update for RN 0.59 since that will be the version to support 64bit on android which becomes mandatory in August 2019.

**Comment by hukid** [comment]
@jbcullis were you able to resolve the issue?

**Comment by jbcullis** [comment]
Using the settings in the update section of the post we got it working however we were never able to pinpoint the random crashes during squares payment workflow....I suspect its eating too much memory.

**Comment by hukid** [comment]
Thanks for confirming that, @jbcullis!

Could you please send us the error information (better with crash callstacks) and we can help to take a look?

**Comment by jbcullis** [comment]
Unfortunately the crashes were all reported by our beta users and we didn't get any info through bugsnag.
The lack of a test environment was an issue for us and have since paused work on the square reader as stripe terminal has been showing more promise for our particular needs.

**Comment by hukid** [comment]
Thanks for taking the time to respond. We understand that you have to do what's best for your business and we appreciate you taking time to consider Square. Your feedback was immensely helpful, and we've been taking action on the issues you mentioned.

In addition to credit card processing, we strive to provide remarkable solutions for your business. I encourage you to reevaluate Square in the future and ensure our suite of developer products align with your expectations.

Please let me know if you have any additional questions. I'm happy to help.
