### ISSUE TITLE
Could not resolve all files for configuration ':app:debugCompileClasspath'. Could not find com.squareup.sdk.reader:reader-sdk-************:1.0.4.

### ISSUE THREAD

**Issue by LeoMosiah** [square/react-native-square-reader-sdk#44]
when trying to integrate the square sdk in a react native project  already created I came across the following error, I follow the install instructions and get the following error: "Could not resolve all files for configuration ':app:debugCompileClasspath'. Could not find com.squareup.sdk.reader:reader-sdk-************:1.0.4."
To make my app work i needed to manually change the readerSdkVersion on 'node_modules/react-native-square-reader-sdk/android/build.gradle' to '1.1.3' this reader sdk version i found following manually the url '"https://sdk.squareup.com/android/com/squareup/sdk/reader/reader-sdk-*****-*************/"

I'm using on my project the "react-native-square-reader-sdk" package version "1.0.3"

**Comment by StephenJosey** [comment]
Thanks for letting us know! You're right: new apps must use the latest version (whatever version is out when the app is created). We'll work on updating the repo.

For the fix: yes, you can just change to `1.1.3` in your `build.gradle` file as you found out. 

Just by the way, the changes for `1.1.3` can be found here: https://docs.connect.squareup.com/changelog/mobile-logs/2019-02-13
