### ISSUE TITLE
authCode throws error

### ISSUE THREAD

**Issue by saravanapriyan95** [square/react-native-square-reader-sdk#49]
authCode throws error -- **null is not an object (evaluating 'RNReaderSDKAuthorization.authorize')** when   trying to get authorize whith my authCode. Can any one help me to get out of it.....

**Comment by StephenJosey** [comment]
Is this for iOS? If so, can you look at the second troubleshooting advice here: https://github.com/square/react-native-square-reader-sdk/blob/master/docs/troubleshooting.md

Please let me know if that doesn't resolve your issue.

**Comment by saravanapriyan95** [comment]
I have gone through the process about how to link Square Reader SDK in react-native. As in the below link
https://docs.connect.squareup.com/payments/readersdk/build-on-ios

**After completing the above steps. I got an error ( IOS )**
fatal error: module 'SquareReaderSDK' not found
@import SquareReaderSDK;
 ~~~~~~~^~~~~~~~~~~~~~~
1 error generated.

**Comment by StephenJosey** [comment]
So just to confirm, you've went through these steps? https://github.com/square/react-native-square-reader-sdk/blob/master/docs/get-started.md

The steps you posted is for the iOS ReaderSDK, not the React Native SDK. They are different SDKs and are set up differently. Please confirm you've went through the above steps successfully.

**Comment by saravanapriyan95** [comment]
Yeah, I have Done the steps above successfully. https://github.com/square/react-native-square-reader-sdk/blob/master/docs/get-started.md

After completing the above steps. I got an error ( IOS )
fatal error: module 'SquareReaderSDK' not found
@import SquareReaderSDK;
~~~~~~~^~~~~~~~~~~~~~~
1 error generated.

**Comment by StephenJosey** [comment]
HI @saravanapriyan95 would you be able to provide a sample repo so we can easily reproduce this error?

**Comment by StephenJosey** [comment]
Also just to double-check, you ran the ruby install command inside the `ios` directory, right? Not the root react-native directory? `ReaderSDK` needs to be installed in the ios directory, or else you would receive this error.

**Comment by SudoPlz** [comment]
If anyone faces the `Module 'SquareReaderSDK' not found` the issue is probably that the iOS project can't find the `SquareReaderSDK.framework` file.

In our case we had moved that file in a sub-directory called frameworks, and Xcode couldn't find it.
If you move that file in the root ios dir, the error will be gone.
