### ISSUE TITLE
Unexpected callback error, Invalid primitive conversion from long to int

### ISSUE THREAD

**Issue by SudoPlz** [square/react-native-square-reader-sdk#53]
Hey there,

we've been receiving this error in production for a while now, here's the full stacktrace:

    java.lang.RuntimeException Unexpected callback error 
        SquareCallback.java:85 com.squareup.server.SquareCallback.unexpectedError
        SquareCallback.java:61 com.squareup.server.SquareCallback.failure
        CallbackRunnable.java:53 shadow.retrofit.CallbackRunnable$2.run
        StoppableHandlerExecutor.java:155 com.squareup.util.StoppableHandlerExecutor$RemovingRunnableWrapper.run
        Handler.java:878 android.os.Handler.handleCallback
        Handler.java:99 android.os.Handler.dispatchMessage
        Looper.java:209 android.os.Looper.loop
        ActivityThread.java:7046 android.app.ActivityThread.main
        Method.java:-2 java.lang.reflect.Method.invoke
        RuntimeInit.java:486 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
        ZygoteInit.java:862 com.android.internal.os.ZygoteInit.main

    Caused by: java.lang.IllegalArgumentException Unexpected Retrofit error:  
        ReceivedResponse.kt:152 com.squareup.receiving.ReceivedResponse$Companion.fromRetrofitError
        Unknown:2 com.squareup.receiving.ReceivedResponse.fromRetrofitError
        SquareEndpoints.java:16 com.squareup.servercall.SquareEndpoints.errorToCallState
        SquareCallback.java:27 com.squareup.server.SquareCallback.failure
        CallbackRunnable.java:53 shadow.retrofit.CallbackRunnable$2.run
        StoppableHandlerExecutor.java:155 com.squareup.util.StoppableHandlerExecutor$RemovingRunnableWrapper.run
        Handler.java:878 android.os.Handler.handleCallback
        Handler.java:99 android.os.Handler.dispatchMessage
        Looper.java:209 android.os.Looper.loop
        ActivityThread.java:7046 android.app.ActivityThread.main
        Method.java:-2 java.lang.reflect.Method.invoke
        RuntimeInit.java:486 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
        ZygoteInit.java:862 com.android.internal.os.ZygoteInit.main

    Caused by: shadow.retrofit.RetrofitError Invalid primitive conversion from long to int 
        RestAdapter.java:400 shadow.retrofit.RestAdapter$RestHandler.invokeRequest
        RestAdapter.java:220 shadow.retrofit.RestAdapter$RestHandler.access$100
        RestAdapter.java:278 shadow.retrofit.RestAdapter$RestHandler$2.obtainResponse
        CallbackRunnable.java:42 shadow.retrofit.CallbackRunnable.run
        ThreadPoolExecutor.java:1167 java.util.concurrent.ThreadPoolExecutor.runWorker
        ThreadPoolExecutor.java:641 java.util.concurrent.ThreadPoolExecutor$Worker.run
        Threads.java:34 com.squareup.util.Threads$1.lambda$newThread$0
        Unknown:2 com.squareup.util.Threads$1$$Lambda$1.run
        Thread.java:919 java.lang.Thread.run

    Caused by: java.lang.IllegalArgumentException Invalid primitive conversion from long to int 
        Field.java:-2 java.lang.reflect.Field.getInt
        Telephony.java:30 com.squareup.util.Telephony.<init>
        Telephony_Factory.java:21 com.squareup.util.Telephony_Factory.get
        Telephony_Factory.java:8 com.squareup.util.Telephony_Factory.get
        AndroidModule_ProvideNetworkTypeFactory.java:22 com.squareup.util.AndroidModule_ProvideNetworkTypeFactory.get
        AndroidModule_ProvideNetworkTypeFactory.java:8 com.squareup.util.AndroidModule_ProvideNetworkTypeFactory.get
        DoubleCheck.java:47 dagger.internal.DoubleCheck.get
        RegisterHttpInterceptor.java:42 com.squareup.server.RegisterHttpInterceptor.intercept
        RealInterceptorChain.java:92 shadow.okhttp3.internal.http.RealInterceptorChain.proceed
        RealInterceptorChain.java:67 shadow.okhttp3.internal.http.RealInterceptorChain.proceed
        GzipRequestInterceptor.java:32 com.squareup.http.GzipRequestInterceptor.intercept
        RealInterceptorChain.java:92 shadow.okhttp3.internal.http.RealInterceptorChain.proceed
        RealInterceptorChain.java:67 shadow.okhttp3.internal.http.RealInterceptorChain.proceed
        ProfilingInterceptor.java:24 com.squareup.server.ProfilingInterceptor.intercept
        RealInterceptorChain.java:92 shadow.okhttp3.internal.http.RealInterceptorChain.proceed
        RealInterceptorChain.java:67 shadow.okhttp3.internal.http.RealInterceptorChain.proceed
        RealCall.java:185 shadow.okhttp3.RealCall.getResponseWithInterceptorChain
        RealCall.java:69 shadow.okhttp3.RealCall.execute
        Ok3Client.java:40 shadow.com.jakewharton.retrofit.Ok3Client.execute
        RestAdapter.java:326 shadow.retrofit.RestAdapter$RestHandler.invokeRequest
        RestAdapter.java:220 shadow.retrofit.RestAdapter$RestHandler.access$100
        RestAdapter.java:278 shadow.retrofit.RestAdapter$RestHandler$2.obtainResponse
        CallbackRunnable.java:42 shadow.retrofit.CallbackRunnable.run
        ThreadPoolExecutor.java:1167 java.util.concurrent.ThreadPoolExecutor.runWorker
        ThreadPoolExecutor.java:641 java.util.concurrent.ThreadPoolExecutor$Worker.run
        Threads.java:34 com.squareup.util.Threads$1.lambda$newThread$0
        Unknown:2 com.squareup.util.Threads$1$$Lambda$1.run
        Thread.java:919 java.lang.Thread.run

We have no idea about how we can reproduce that, because we're receiving it in bugsnag and there are no clear indications as to when that happens, but ALL of the errors took place on Android Q.

We're using version 1.0 of your react-native sdk, I'm wondering if that's a known issue that's fixed.

Thank you

**Comment by hukid** [comment]
@SudoPlz you are right, it's fixed in latest Android SDK 1.2.1.

**Comment by SudoPlz** [comment]
Got it, so that's fixed on 1.2.0, any ETA's on that?

**Comment by hukid** [comment]
If you upgrade you plugin to 1.2.0, you'll get Android SDK 1.2.1 support.
