### ISSUE TITLE
Device is not supported

### ISSUE THREAD

**Issue by tuannguyenhoangit** [square/react-native-square-reader-sdk#57]
After connect wireless reader. The app show device is not supported. 
I am use Rockchip android 22 
https://sc01.alicdn.com/kf/HTB1HIKEXvfsK1RjSszbq6AqBXXaX/kassensystem-metal-ecr-cash-register-all-in.jpg_220x220.jpg

**Comment by tuannguyenhoangit** [comment]
https://stackoverflow.com/questions/56274036/square-sdk-cant-pair-reader-through-bluetooth

**Comment by hukid** [comment]
@tuannguyenhoangit has your issue been resolved?

**Comment by StephenJosey** [comment]
Closing due to no response. Please reopen if you're still having an issue, though!
