### ISSUE TITLE
Reference id field on checkout

### ISSUE THREAD

**Issue by ochicf** [square/react-native-square-reader-sdk#60]
Hi!

Is it possible to set the reference id on the checkout? I would like to send the id of a record in my back-end so I can relate it with the transaction using a webhook, and I was hoping to do it using the reference id (as seen [here](https://developer.squareup.com/docs/transactions-api/build-with-transactions#step-4-set-the-transaction-metadata) and [here](https://github.com/square/connect-javascript-sdk/blob/5c69a3054e112ab10a0b651f33d8371a7485c13e/docs/ChargeRequest.md)) instead of the `note` field.

Thank you in advance!

**Comment by StephenJosey** [comment]
Hi @ochicf unfortunately this is not currently supported, but I'll be sure to share this feedback with our Developers team.
