### ISSUE TITLE
Support countries other than the US

### ISSUE THREAD

**Issue by botoxparty** [square/react-native-square-reader-sdk#63]
### Describe the functionality you would like to see

Would love to see this project become available to all regions, not just the United States,

Don't think it needs much more explanation than that, or what the benefits would be...

Happy to dedicate some resources to making this happen.

**Comment by hukid** [comment]
Thanks for the feedback and yes we are working on that!

**Comment by jameslevine** [comment]
Any idea when this might be happening?

**Comment by StephenJosey** [comment]
Please reach out to https://squareup.com/help/us/en/contact?panel=BF53A9C8EF68 if you still are interested in this. Thanks!

**Comment by sseaman** [comment]
Closing as there are no set plans to support this.  We'll keep this in mind however.
