### ISSUE TITLE
No AndroidX Support

### ISSUE THREAD

**Issue by mattknappchhj** [square/react-native-square-reader-sdk#67]
### Describe the issue

There is currently no support for migration to AndroidX due to DateFormatUtils Libary in internals folder.

Suggestion would be to remove _import android.support.annotation.NonNull;_ and replace with _import androidx.annotation.NonNull;_ This will allow for future proofing with AndroidX

### To Reproduce

Simply use a clean install and Refactor->Migrate to AndroidX

### Expected behavior

Should migrate cleanly to AndroidX

**Environment (please complete the following information):**

**Comment by hukid** [comment]
@mattknappchhj , we are currently working on adding Android X support. 

Did you try https://github.com/mikehardy/jetifier to workaround this issue?

**Comment by hukid** [comment]
@dibelogrivaya I think this issue is resolved now. Take a look this changelog: https://github.com/square/react-native-square-reader-sdk/blob/master/CHANGELOG.md#v122-september-10-2019

Please let me know if that's what you want.

**Comment by dibelogrivaya** [comment]
I have error in latest version:
`node_modules/react-native-square-reader-sdk/android/src/main/java/com/squareup/sdk/reader/react/internal/DateFormatUtils.java:18: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;`

When I change `import android.support.annotation.NonNull;` to `import androidx.annotation.NonNull;` and everything works

**Comment by dibelogrivaya** [comment]
@hukid this error occurs with the following dependencies:
`"@jumpn/react-native-jetifier": "^0.1.4",`
`"react-native": "0.61.3"`
Please, fix it in next release. Thanks!

**Comment by seankwalker** [comment]
Hello @hukid! Noticed that version 1.3.1 (with the fix for this issue) is in the CHANGELOG but there does not seem to be a corresponding version on npm--is it still in development?

**Comment by StephenJosey** [comment]
1.3.1 is in npm now, published 14 days ago. Closing this, but please let us know if you continue having issues.
