### ISSUE TITLE
squarereadersdk Not found

### ISSUE THREAD

**Issue by saravanapriyan95** [square/react-native-square-reader-sdk#68]
While installing the application in the IOS Simulator in have faced an issue i.e (Module 'SquareReaderSDK' not found ). Can u help me to resolve the following issue ASAP

**Comment by hukid** [comment]
@saravanapriyan95 Did you install the ReaderSDK by following this document?
https://github.com/square/react-native-square-reader-sdk/blob/master/docs/get-started.md#step-5-install-reader-sdk-for-ios

**Comment by StephenJosey** [comment]
Closing this due to no response. Please comment/reopen if you are still having this issue. Thanks!
