### ISSUE TITLE
Problems with setup script

### ISSUE THREAD

**Issue by spookymodem** [square/react-native-square-reader-sdk#70]
### Describe your question

I am attempting to build an iOS app that uses this library and am unable to build the app due to problems with the setup shell script.

My first problem is that the script does not exist in the required location during build time. The script should be located here: ${FRAMEWORKS}/SquareReaderSDK.framework/setup
However, I have checked that directory and found no setup script.

My other problem is with the contents of the setup script. In the code-signing section near the end, there are two variables that are not defined in the script:
CODESIGNING_FOLDER_PATH
EXPANDED_CODE_SIGN_IDENTITY

Has anyone experienced similar problems?  Thanks!

**Comment by katyechhj** [comment]
Did you ever find a solution to this?
