### ISSUE TITLE
Expo compatibility

### ISSUE THREAD

**Issue by RumenTech** [square/react-native-square-reader-sdk#89]
### Describe your question
Square Readers is the core functionality React Native application I'm going to build. Does anybody know if I can start my app with **Expo**?

**Comment by okenshields** [comment]
I've never used Expo personally. Have you had success trying it out?

**Comment by Spacarar** [comment]
as far as I've read libraries that use native iOS or android code cannot be used with expo. I believe that this would be one such library as it uses native code.

so in short. No to use this library you will need a full react-native app using either `react-native init` or `react-native eject` if you already created the project using expo https://docs.expo.io/versions/latest/expokit/eject/

**Comment by StephenJosey** [comment]
What @Spacarar is correct as far as I know, as well. Going to close this out since this has been answered. Please comment if you have further questions/concerns.
