### ISSUE TITLE
SquareReaderSDK not found

### ISSUE THREAD

**Issue by bradmurphy** [square/react-native-square-reader-sdk#92]
I've followed the installation on this correctly, did this a couple months ago and didn't have any problems.  Now when I'm running my build the react-native-square-reader-sdk is having a problem finding `SquareReaderSDK` in the node modules.

Specifically this file:  In file included from node_modules/react-native-square-reader-sdk/ios/Converters/SQRDTenderCardDetails+RNReaderSDKAdditions.m:

It's failing to recognize the import.  The Framework is installed and linked, just errors every time I try to run my project.

**Comment by okenshields** [comment]
@bradmurphy, thanks for reporting the issue. Can you also help clarify a few things:
- Are you trying to run the example app (in https://github.com/square/react-native-square-reader-sdk/tree/master/reader-sdk-react-native-quickstart) or did you create your own app?
- Which version of Reader SDK did you install? There was a new Reader SDK release last month (https://developer.squareup.com/docs/changelog/mobile-logs/2019-09-25) and you may need to delete the old one and re-download.
- Which iOS version are you targeting? Reader SDK 1.3.3 is required to support iOS 13.

**Comment by muhammadashfaq** [comment]
i am also facing this issue
`Module 'SquareReaderSDK' not found`

Please help me to solve this issue  i have followed all the steps of installtion

**Comment by bradmurphy** [comment]
@muhammadashfaq I've reinstalled the framework a couple times now.  I've also upgraded macOS and XCode, now I'm getting a shell script error for my pods.  I've reinstalled the pods dozens of times now and it's still not recognizing the pod install.

Shell Script Invocation Error Group
Diff: /Podfile.lock: No such file or directory
Diff: /Manifest.lock: No such file or directory
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

I've deleted the podfile.lock, deleted the pod directory, cleaned the pod cache as well as everything else and it's still not running properly after installing all of that.  Can't get past this error.

**Comment by DungBuiDeveloper** [comment]
same issue anyone have solution

**Comment by StephenJosey** [comment]
Hey folks - we're still looking into this. Apologies about the delay, but we'll update this ticket as soon as we have more information, or a fix in place. Thanks for your patience.

**Comment by DungBuiDeveloper** [comment]
make step 3 in ios folder please

**Comment by rahamin1** [comment]
I have an android build working for several months.
Just tried to build for iOS and I am getting the same problem.

@DungBuiDeveloper What do you mean by `make step 3 in ios folder please`?

**Comment by DungBuiDeveloper** [comment]
> I have an android build working for several months.
> Just tried to build for iOS and I am getting the same problem.
> 
> @DungBuiDeveloper Can you please explain what you mean by `make step 3 in ios folder`?

https://github.com/square/react-native-square-reader-sdk/tree/master/reader-sdk-react-native-quickstart

step 3 in that link , this is quick start for react native

**Comment by rahamin1** [comment]
I see. My problem is on iOS...
On android it is working fine.

@StephenJosey is there a workaround for iOS?

**Comment by DungBuiDeveloper** [comment]
> I see. My problem is on iOS...
> On android it is working fine.

could i help you some thing , i installed success on IOS .

**Comment by DungBuiDeveloper** [comment]
> > I see. My problem is on iOS...
> > On android it is working fine.
> 
> could i help you some thing , i installed success on IOS .

bui.tuandung1 <<, this is my skype contact

**Comment by rahamin1** [comment]
Wow, thanks a lot! Since it is my first build on iOS, and I am not very good at iOS, I have many issues. 
When I saw that the setup on iOS is complex, I am trying to start without it now, I hope that everything else will work, then I will do it.
I will write here hopefully soon.  Thank you very much! I appreciate it a lot!

**Comment by DungBuiDeveloper** [comment]
> Wow, thanks a lot! Since it is my first build on iOS, and I am not very good at iOS, I have many issues.
> When I saw that the setup on iOS is complex, I am trying to start without it now, I hope that everything else will work, then I will do it.
> I will write here hopefully soon. Thank you very much! I appreciate it a lot!

hope success ! i think easy if use quick start guild .

**Comment by rahamin1** [comment]
Meanwhile, if you can help with this:
https://github.com/square/in-app-payments-react-native-plugin/issues/66
