### ISSUE TITLE
Frameworks/SquareReaderSDK.framework/setup: No such file or directory when building for react-native 0.60.5

### ISSUE THREAD

**Issue by katyechhj** [square/react-native-square-reader-sdk#97]
### Describe the issue
  When I try to build my project in xcode, I get an error saying:
Frameworks/SquareReaderSDK.framework/setup: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

  Error log details:
  ```
  /Users/katye/Library/Developer/Xcode/DerivedData/HunkSquadv2-fwguotvgreavojcyfmgepmznkasw/Build/Intermediates.noindex/HunkSquadv2.build/Debug-iphonesimulator/HunkSquadv2.build/Script-0A78BC7D23735553005322EC.sh: line 4: /Users/katye/Library/Developer/Xcode/DerivedData/HunkSquadv2-fwguotvgreavojcyfmgepmznkasw/Build/Products/Debug-iphonesimulator/HunkSquadv2.app/Frameworks/SquareReaderSDK.framework/setup: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
  ```

**Environment (please complete the following information):**
  - platform: iOS
  - OS and version: iOS 
  - dev environment: MacOS Catalina 10.15
  - Reader SDK version: 1.3.0

System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 782.69 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-create-library: 3.1.2
    react-native: 0.55.4

### Additional context
The documentation given in the get-started.md file doesn't seem to be up to date with the react native 0.60 release. I'm honestly at a loss of what to do to fix the problem. Any help would be greatly appreciated!

This project is using react-native 0.60.5

**Comment by caseycole589** [comment]
I am also experiencing this issue.

**Comment by asmengel** [comment]
This is the same problem i have been experiencing

**Comment by jgorecki** [comment]
Following

**Comment by katyechhj** [comment]
In case anyone else runs into this problem, make sure the "Run Script" given in the documentation is below "Embed Frameworks" on the Build Phases tab in Xcode. My project builds again! :)
