### ISSUE TITLE
Support for the Square Payments API

### ISSUE THREAD

**Issue by joelthesellout** [square/react-native-square-reader-sdk#98]
### Describe the functionality you would like to see
Currently the Square Reader SDK only supports the deprecated Square Transactions API. If it supported the new Payments API, it would be much more up to date with Squares new feature sets.

### How would this feature make the plugin more useful?
This would be particularly valuable to my company because we require the ability to collect fees on in-person payments as well as payments made on our website. If we could collect fees on in person transactions we would switch from Stripe to Square in a heartbeat.

**Comment by okenshields** [comment]
Hi Joel,

Glad to know you are exploring Reader SDK. Great feedback! If it's ok, can you leave an email address so we can contact you to further discuss potential solutions to your problem? Thanks!

**Comment by CharmisG** [comment]
Thank you for your feedback. We have shared the feedback with our team.
